// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

// State de Pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';

export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

export const GUARDAR_PEDIDO = 'GUARDAR_PEDIDO';

export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';
